### ISSUE TITLE
package resolution failed

### ISSUE THREAD

**Issue by futurepaul** [bitcoindevkit/bdk-swift#1]
<img width="695" alt="Screen Shot 2021-11-30 at 7 53 32 AM" src="https://user-images.githubusercontent.com/543668/144059824-1488ceee-0c1d-41fa-8728-dff3f50516e1.png">

running xcode 13.1 on an M1 mac

if I click "add anyway" it's added to my project but doesn't do anything

**Comment by notmandatory** [comment]
Thanks for testing! which tag did you use? The only one that works is `0.1.3` (I'll remove the others I created while testing).

**Comment by notmandatory** [comment]
You may also have problems if you're trying to use this package on an M1 mac (ios simulator, or macos), I haven't added binaries in the xcframework for M1 macos and not sure how the ios simulator works on the M1 since it's also `aarch64` just like the current phone hardware.  But I can confirm that I'm able to cross-compile the M1 macos rust target `aarch64-apple-darwin` on my `x86_64` macbook (which was added with [rust 1.49.0](https://blog.rust-lang.org/2020/12/31/Rust-1.49.0.html)).

**Comment by futurepaul** [comment]
yeah I'm using 0.1.3.

**Comment by futurepaul** [comment]
resolved by https://github.com/bitcoindevkit/bdk-swift/commit/a33e856b48379008b5c0b6cfa624f790474d2859 thank you!

**Comment by notmandatory** [comment]
thanks @futurepaul for testing this and confirming it works on an M1!
