### ISSUE TITLE
No way of getting block hash and block height

### ISSUE THREAD

**Issue by danielnordh** [bitcoindevkit/bdk-swift#10]
I'm trying to use BDK with LDK, but it appears I am blocked at the moment by the lack of exposure of the blockchain object in Swift.

**Comment by notmandatory** [comment]
To resolve this issue we need to do a few upstream changes:
- [ ] Update `bdk-ffi` to allow construction of a `Blockchain` outside of the `Wallet`.
- [ ] Make sure the new `Blockchain` object in `bdk-ffi` exposes the `get_height` function.
- [ ] Update `Blockchain` in `bdk` to include a `get_block_hash` function and expose that in `bdk-ffi`.

As we get issues/PRs for these I'll update here to help track.

**Comment by notmandatory** [comment]
https://github.com/bitcoindevkit/bdk-ffi/issues/143 should tick the first two boxes above.

**Comment by notmandatory** [comment]
@danielnordh for a new `Blockchain.get_block_hash` function, does it only need to return the block hash at a given height? Or do you need something else?

**Comment by danielnordh** [comment]
> @danielnordh for a new `Blockchain.get_block_hash` function, does it only need to return the block hash at a given height? Or do you need something else?

I'm not sure yet to be honest :)
Trying to use BDK as a source for LDK, so whatever that needs.

**Comment by ConorOkus** [comment]
It would need to return the latest block hash & latest block height

**Comment by notmandatory** [comment]
Currently the `bdk`  [`blockchain::GetHeight`] trait exists and we can expose it from the `bdk-ffi` `Blockchain` interface for Swift and the other languages, but we aren't exposing any interface to get a block hash at the latest block height. 

It looks like it is possible to get a block hash info from the blockchain clients `bdk-ffi` is currently supporting, [Esplora API] and [Electrum API]. I think the only reason get block hash isn't implemented is because it isn't needed for syncing wallet transactions with `bdk`, but if exposing it will make it possible to support `ldk` then I think it's worth doing. I created issues for `bdk` and `bdk-ffi` with links back to this issue.

  - [ ]  https://github.com/bitcoindevkit/bdk/issues/603
  - [ ] https://github.com/bitcoindevkit/bdk-ffi/issues/151

[Esplora API]:https://github.com/Blockstream/esplora/blob/master/API.md#get-block-heightheight
[Electrum API]:https://electrumx.readthedocs.io/en/latest/protocol-methods.html#blockchain-block-header
[`blockchain::GetHeight`]:https://docs.rs/bdk/latest/bdk/blockchain/trait.GetHeight.html

**Comment by danielnordh** [comment]
> It looks like it is possible to get a block hash info from the blockchain clients bdk-ffi is currently supporting, [Esplora API](https://github.com/Blockstream/esplora/blob/master/API.md#get-block-heightheight) and [Electrum API](https://electrumx.readthedocs.io/en/latest/protocol-methods.html#blockchain-block-header). I think the only reason get block hash isn't implemented is because it isn't needed for syncing wallet transactions with bdk, but if exposing it will make it possible to support ldk then I think it's worth doing. I created issues for bdk and bdk-ffi with links back to this issue.

Thank you! It would help immensely and should make BDK able to support LDK without the need for other code.

**Comment by thunderbiscuit** [comment]
These features were merged on the FFI master branch yesterday, and will be available in the next release of bdk-swift.

**Comment by notmandatory** [comment]
This should be in the bdk-swift 0.5.x release.
